"""Orchestrator Agent Pattern Logic."""

from google.adk.agents import LlmAgent
from pydantic import BaseModel, Field

from patterns.config import GEMINI_MODEL

# --- Data Models ---


class SubTask(BaseModel):
    """A single sub-task for a worker."""

    title: str = Field(description="Short title of the sub-task")
    description: str = Field(description="Detailed instructions for the worker")
    worker_type: str = Field(
        description=(
            "The type of persona needed (e.g., 'Researcher', 'Creative Writer', "
            "'Fact Checker')"
        ),
    )


class ExecutionPlan(BaseModel):
    """The complete plan generated by the Orchestrator."""

    plan_title: str = Field(description="Overarching goal of the plan")
    tasks: list[SubTask] = Field(
        description="List of tasks to be performed in parallel",
    )


# --- Agent Definitions ---

# 1. The Orchestrator (Planner)
orchestrator_agent = LlmAgent(
    name="Orchestrator",
    model=GEMINI_MODEL,
    instruction="""You are an expert Project Manager and Orchestrator.
Your goal is to take a complex user request and break it down into 2-4 independent,
well-defined sub-tasks that can be executed in parallel by specialized workers.

Focus on:
- Modularity: Each task should be self-contained.
- Clarity: Provide clear instructions for each worker.
- Synergy: Ensure the combined output of these tasks will cover the original request.
""",
    output_schema=ExecutionPlan,
)


# 2. The Worker (Executor)
# We use a factory function or a generic agent that can be customized.
def create_worker_agent(name: str, instruction: str) -> LlmAgent:
    """Create a worker agent for a specific sub-task.

    Args:
        name: The name of the worker agent.
        instruction: The instruction for the worker agent.

    Returns:
        An instance of LlmAgent.

    """
    # Sanitize name to be a valid identifier
    safe_name = "".join(c if c.isalnum() else "_" for c in name)
    if not safe_name or not safe_name[0].isalpha():
        safe_name = f"worker_{safe_name}"

    return LlmAgent(
        name=safe_name,
        model=GEMINI_MODEL,
        instruction=instruction,
    )


# 3. The Synthesizer (Aggregator)
synthesizer_agent = LlmAgent(
    name="Synthesizer",
    model=GEMINI_MODEL,
    instruction="""You are a Meta-Aggregator and Final Reviewer.
You will receive the original user request and the outputs from
multiple specialized workers.
Your task is to synthesize these inputs into a final, cohesive,
and high-quality response that directly addresses the user's original goal.

Ensure the final output is:
- Unified: It shouldn't look like a collection of separate parts.
- Polished: Fix any inconsistencies or redundancies.
- Comprehensive: Check that all parts of the user's initial request are met.
""",
)
